CREATE TABLE "GCG_5744_FRGHT_OTH" PAGESIZE=4096 (
 "PO" CHAR(7),
 "FREIGHT" NUMERIC(12,4),
 "OTHER" NUMERIC(12,4),
 "FRT_VENDOR" CHAR(30),
 "FRT_VENDOR_CODE" CHAR(6),
 "FRT_PO" CHAR(7),
 "FLAG_FRTPO_RECEIVED" CHAR(1) );
